In [3]:
from google.colab import files
uploaded = files.upload()

Saving avocado.csv to avocado.csv
Saving ramen-ratings.csv to ramen-ratings.csv

###**Project 6-1: Clean the Ramen Data**

In [4]:
# Load ramen data
ramen = pd.read_csv("ramen-ratings.csv")
print("Original rows:", len(ramen))
ramen.head()

Original rows: 2577

,Brand,Variety,Style,Country,Stars
0,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75
1,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1.00
2,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25
3,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75
4,Ching's Secret,Singapore Curry,Pack,India,3.75

In [5]:
# 1. Rename Stars → Rating
ramen.rename(columns={"Stars": "Rating"}, inplace=True)

In [6]:
# 2. Convert Style column to category type
ramen["Style"] = ramen["Style"].astype("category")

In [ ]:
# 3. Drop the Country column
ramen.drop(columns=["Country"], inplace=True)

In [7]:
# 4. Check changes
print(ramen.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2577 entries, 0 to 2576
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Brand    2577 non-null   object
 1   Variety  2577 non-null   object
 2   Style    2575 non-null   category
 3   Country  2577 non-null   object
 4   Rating   2577 non-null   float64
dtypes: category(1), float64(1), object(3)
memory usage: 83.5+ KB
None

In [8]:
# 5. Rename Brand → Company, Variety → Product
ramen.rename(columns={"Brand": "Company", "Variety": "Product"}, inplace=True)

In [9]:
# 6. Show duplicates on Company/Product
dupes = ramen[ramen.duplicated(subset=["Company","Product"], keep=False)]
print("Duplicate Company/Product rows:\n", dupes)

Duplicate Company/Product rows:
               Company                          Product Style      Country  \
2              Nissin    Cup Noodles Chicken Vegetable   Cup          USA
24     Ching's Secret       Hot Garlic Instant Noodles  Pack        India
46           Nongshim                Shin Ramyun Black  Pack  South Korea
69            MyKuali  Penang Red Tom Yum Goong Noodle  Pack     Malaysia
75           Nongshim                      Shin Ramyun  Pack  South Korea
...               ...                              ...   ...          ...
2545             Koka           Mi Hai Cua Crab Flavor  Pack    Singapore
2552           Nissin         Demae Ramen Spicy Flavor  Pack        Japan
2556         Nongshim        Champong Oriental Noodles  Pack  South Korea
2558         Nongshim                      Shin Ramyun  Pack  South Korea
2565  Sapporo Ichiban                    Shrimp Flavor  Pack        Japan

      Rating
2       2.25
24      4.25
46      5.00
69      5.00
75      3.00
...      ...
2545    3.50
2552    3.00
2556    4.00
2558    4.00
2565    2.50

[118 rows x 5 columns]

In [10]:
# 7. Drop duplicates except first
ramen_nodupes = ramen.drop_duplicates(subset=["Company","Product"], keep="first")
print("Rows after removing duplicates:", len(ramen_nodupes))

Rows after removing duplicates: 2517

In [11]:
# 8. Drop missing values
ramen_clean = ramen_nodupes.dropna()
print("Final rows after dropping NA:", len(ramen_clean))
ramen_clean.head()

Final rows after dropping NA: 2515

,Company,Product,Style,Country,Rating
0,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75
1,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1.00
2,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25
3,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75
4,Ching's Secret,Singapore Curry,Pack,India,3.75

###**Project 6-2: Clean the Avocado Data**

In [12]:
# Load avocado data
avocado = pd.read_csv("avocado.csv")
avocado.head()

,Unnamed: 0,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
4,4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany

In [13]:
# 1. Check missing values
print(avocado.isnull().sum())

Unnamed: 0      0
Date            0
AveragePrice    0
Total Volume    0
4046            0
4225            0
4770            0
Total Bags      0
Small Bags      0
Large Bags      0
XLarge Bags     0
type            0
year            0
region          0
dtype: int64

In [14]:
# 2. Unique values in region column
print("Unique regions:", avocado["region"].unique())

Unique regions: ['Albany' 'Atlanta' 'BaltimoreWashington' 'Boise' 'Boston'
 'BuffaloRochester' 'California' 'Charlotte' 'Chicago' 'CincinnatiDayton'
 'Columbus' 'DallasFtWorth' 'Denver' 'Detroit' 'GrandRapids' 'GreatLakes'
 'HarrisburgScranton' 'HartfordSpringfield' 'Houston' 'Indianapolis'
 'Jacksonville' 'LasVegas' 'LosAngeles' 'Louisville' 'MiamiFtLauderdale'
 'Midsouth' 'Nashville' 'NewOrleansMobile' 'NewYork' 'Northeast'
 'NorthernNewEngland' 'Orlando' 'Philadelphia' 'PhoenixTucson'
 'Pittsburgh' 'Plains' 'Portland' 'RaleighGreensboro' 'RichmondNorfolk'
 'Roanoke' 'Sacramento' 'SanDiego' 'SanFrancisco' 'Seattle'
 'SouthCarolina' 'SouthCentral' 'Southeast' 'Spokane' 'StLouis' 'Syracuse'
 'Tampa' 'TotalUS' 'West' 'WestTexNewMexico']

In [15]:
# 3. Drop rows where region == "TotalUS"
avocado = avocado[avocado["region"] != "TotalUS"]
print("Rows after dropping TotalUS:", len(avocado))

Rows after dropping TotalUS: 17911

In [16]:
# 4. Drop unwanted columns
avocado = avocado.drop(columns=["Unnamed: 0","4046","4225","4770"], errors="ignore")

In [17]:
# 5. Convert Date column to datetime
avocado["Date"] = pd.to_datetime(avocado["Date"])

In [18]:
# 6. Check final DataFrame
print(avocado.info())
avocado.head()

<class 'pandas.core.frame.DataFrame'>
Index: 17911 entries, 0 to 18248
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          17911 non-null  datetime64[ns]
 1   AveragePrice  17911 non-null  float64
 2   Total Volume  17911 non-null  float64
 3   Total Bags    17911 non-null  float64
 4   Small Bags    17911 non-null  float64
 5   Large Bags    17911 non-null  float64
 6   XLarge Bags   17911 non-null  float64
 7   type          17911 non-null  object
 8   year          17911 non-null  int64
 9   region        17911 non-null  object
dtypes: datetime64[ns](1), float64(6), int64(1), object(2)
memory usage: 1.5+ MB
None

,Date,AveragePrice,Total Volume,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,2015-12-27,1.33,64236.62,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,2015-12-20,1.35,54876.98,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,2015-12-13,0.93,118220.22,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,2015-12-06,1.08,78992.15,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
4,2015-11-29,1.28,51039.60,6183.95,5986.26,197.69,0.0,conventional,2015,Albany